version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:18-alpine

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true

      - run:
          name: name: Build Docker Image
          command: |
            docker build -t your-dockerhub-username/krypto-punks-smart-contracts .
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Frontend Image
          command: |
            docker tag frontend:latest $DOCKERHUB_USERNAME/frontend:latest
            docker push $DOCKERHUB_USERNAME/frontend:latest
      - run:
          name: Push Backend Image
          command: |
            docker tag backend:latest $DOCKERHUB_USERNAME/backend:latest
            docker push $DOCKERHUB_USERNAME/backend:latest
      